name: Rebase PR on Upstream Main

on:
  pull_request:
    branches:
      - main

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Setup Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add Upstream and Fetch Changes
        run: |
          git remote add upstream https://github.com/Cinnamon/kotaemon
          git fetch upstream main

      - name: Rebase PR branch onto upstream/main
        run: |
          git rebase upstream/main

      - name: Push Rebased Branch (if successful)
        run: |
          git push origin HEAD --force

